name: Deploy Backend API

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to virtual machine
        run: |
          ssh azureuser@20.2.74.158 "cd /path/to/deploy && git pull origin master && npm install && pm2 restart all"
