name: Deploy Backend API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          npm install
          if [ $? -ne 0 ]; then
            echo "Error: Failed to install dependencies"
            exit 1
          fi

      - name: Deploy code to VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /path/to/your/app || exit 1
            git pull origin main || exit 1
            npm install || exit 1
            pm2 restart server.js || exit 1

      - name: Test Deployment
        run: |
          response=$(curl -s -o /dev/null -w "%{http_code}" http://$HOST/sayHello)
          if [ "$response" != "200" ]; then
            echo "Error: Failed to test deployment"
            exit 1
          fi
