name: Deploy Backend API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Deploy code to VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /path/to/your/app  # Navigate to your app directory
            git pull origin main  # Pull latest changes from main branch
            npm install           # Install dependencies
            pm2 restart server.js # Restart your Node.js server

      - name: Test Deployment
        run: curl http://$HOST/sayHello
