name: Deploy Backend API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa


          
      - name: Connect VM
        shell: pwsh
        run: |
            echo "Running script on VM..."
            $hhost = "20.2.74.158"
            $uusername = "azureuser"
            echo "helloyo"
            $private = "${{ secrets.SSH_PRIVATE_KEY }}"
            echo "hello"
            echo $hhost $uusername              # Ensure that the PowerShell commands are valid for your use case and environment.

            
            $script = @"
              #!/bin/bash
              # Your Bash script content here
              echo "Hello, world"
              # cd "/path/to/BackendAssignment/HelloApi" || exit 1
              # git pull origin main || exit 1
              # npm install || exit 1
              # pm2 restart index.js || exit 1
            "@
            ssh -i ~/.ssh/id_rsa $uusername@$hhost "$script"
            echo "VM connected"

      - name: Deploy code to VM
        shell: pwsh
        run: |
            echo "Running script on VM..."
            cd D:\BackendAssignment\HelloApi || (echo "Failed to change directory" && exit 1)
            echo "Changed directory successfully"
            git pull origin main || (echo "Failed to pull from Git repository" && exit 1)
            echo "Git pull successful"
            pm2 restart index.js || (echo "Failed to restart application with pm2" && exit 1)
            echo "Application restarted successfully"

      - name: Test Deployment
        run: |
          response=$(curl -s -o /dev/null -w "%{http_code}" http://$HOST/sayHello)
          if [ "$response" != "200" ]; then
            echo "Error: Failed to test deployment"
            exit 1
          fi
